### ISSUE TITLE
Y u no SSL

### ISSUE THREAD

**Issue by todb-r7** [craiga/will-of-the-prophets#212]
Hey there, friend of DeSoto! Let's get a little LetsEncrypt action on this here Game of Buttholes web app! It's easy and fun, and makes for a more pleasant URL bar (aside from, ya know, securing stuff and making crypto the norm).

If you want me to do it for you, just hand over some admin creds and I'd be happy to. Check my commit history, I'm as trustworthy as a Dabo girl!

**Comment by craiga** [comment]
Ha, I'm sure you are.

will-of-the-prophets.herokuapp.com itself supports SSL though Heroku magic. I guess that's Let's Encrypt behind the scenes.

It should automatically redirect to HTTPS. There's probably a Django setting which does this automatically. In fact, somebody should go through [Adam Johnson's suggestions from DjangCon Europe](https://adamj.eu/tech/2019/04/10/how-to-score-a+-for-security-headers-on-your-django-website/) and implement them, too.

gagh.biz is managed by Adam & Ben, and I'm not sure what's involved in getting that working with HTTPS.

**Comment by todb-r7** [comment]
Sounds like a WONTFIX, then -- https://gagh.biz/game is still not a thing.

**Comment by craiga** [comment]
Yeah, gagh.biz is managed by Adam & Ben. I'm not sure what's involved in getting that working with HTTPS. It's got nothing to do with the game though.
