### ISSUE TITLE
Special square images missing for Traveler and Bangers

### ISSUE THREAD

**Issue by willettk** [craiga/will-of-the-prophets#79]
Possibly related to #73. No idea if the images are still waiting to created, but they don't show up on the main page as of now. URLs point to dead links:

* https://will-of-the-prophets.herokuapp.com/special_square/icon_traveler_no_background_small_8lxdN4h.png
* https://will-of-the-prophets.herokuapp.com/special_square/icon_banger_no_background_small_OfvBQJA.png

**Comment by craiga** [comment]
Thanks for the report! For some reason I’d assumed whitenoise handles uploads. It doesn’t. This has been fixed in #80.
